// Generated by CoffeeScript 1.6.3
var QAdata;

QAdata = [
  {
    q: "这是第一题,正确答案是D",
    type: "checkbox",
    fraction: 1,
    a: [
      {
        title: "我是A,我是错的",
        right: false
      }, {
        title: "我是B,我是错的",
        right: false
      }, {
        title: "我是C,题是错的",
        right: true
      }, {
        title: "我是D,我是错的",
        right: false
      }
    ]
  }, {
    q: "这是第二题,正确答案是不对的",
    type: "radio",
    fraction: 1,
    a: [
      {
        title: "正确答案",
        right: false
      }, {
        title: "不对的",
        right: true
      }
    ]
  }, {
    q: "这是第三题, 你上面两道题答对了吗?",
    type: "radio",
    fraction: 1,
    a: [
      {
        title: "对了",
        right: false
      }, {
        title: "错了",
        right: false
      }, {
        title: "不知道",
        right: true
      }
    ]
  }, {
    q: "这是第四题,这个破玩意的作者是谁?",
    type: "checkbox",
    fraction: 1,
    a: [
      {
        title: "kelvin",
        right: true
      }, {
        title: "桥哥",
        right: true
      }, {
        title: "上面两个是一个人",
        right: true
      }, {
        title: "爱谁谁",
        right: false
      }
    ]
  }
];
